# https://djoser.readthedocs.io/en/latest/base_endpoints.html
//creare cont 

POST http://localhost:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "email" : "andreidurdun2@gmail.com",
    "first_name" : "Andrei",
    "last_name" : "Durdun",
    "password" : "12345678Abc",
    "re_password" : "12345678Abc"
}


//activare contul
//uid = in url-ul din email, dupa activate/
//token = in url dupa uid
###
POST http://localhost:8000/auth/users/activation/ HTTP/1.1
Content-Type: application/json

{
    "uid" : "NQ",
    "token" : "cox3rs-2fbf83fe36a51522e40968b02c602c8d"
}

###
POST http://localhost:8000/auth/users/resend_activation/ HTTP/1.1
Content-Type: application/json

{
    "email" : "andreidurdun2@gmail.com"
}

//login
# https://djoser.readthedocs.io/en/latest/jwt_endpoints.html

###
POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email" : "andreidurdun2@gmail.com",
    "password" : "12345678Abc"

}

###
//DELETE Account
DELETE http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NzUzNTk2LCJpYXQiOjE3NDU3NDk5OTYsImp0aSI6ImM1ZjJlMTg3ZDc3ZjQzZjBhMWY3YWI3OTgxMzdlY2Y2IiwidXNlcl9pZCI6Mn0.AqKl1TkwWx3V9p8ToFbb7wAr8QVkD7fqy3qj5d-LnFs
Content-Type: application/json

{
    "current_password" : "12345678Abc"
}

//autentificarea cu google

###
//aceasta cerere se realizeaza din frontend  (tutorial part 10, de la min 20)
//redirect_uri = ulr-ul unde vrei sa te duca dupa autentificare
GET http://localhost:8000/auth/o/google-oauth2/?redirect_uri=http://localhost:8000 HTTP/1.1

###
GET http://localhost:8000/auth/o/google-oauth2/?redirect_uri=http://localhost:8000/complete/google-oauth2/ HTTP/1.1
