
### //testare API Books
GET http://localhost:8000/api/books/search/?author=mihai eminescu HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTc5NTQ3LCJpYXQiOjE3NDU1NzU5NDcsImp0aSI6ImQyNDM0YmM2ZjJjYTQwNDdhOGQ5NDQ5M2ZiZDY5Y2QzIiwidXNlcl9pZCI6MX0.ISLucib6sFchMQKggZQnRuBDM1v564Jec9B8_C6tYck

### //returnare catri dupa categorie
GET http://localhost:8000/api/books/category/?name=popular HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTc5NTQ3LCJpYXQiOjE3NDU1NzU5NDcsImp0aSI6ImQyNDM0YmM2ZjJjYTQwNDdhOGQ5NDQ5M2ZiZDY5Y2QzIiwidXNlcl9pZCI6MX0.ISLucib6sFchMQKggZQnRuBDM1v564Jec9B8_C6tYck
//recent = Recently Published
//popular = Popular Now