
### //testare API Books
// /? {author, title, publisher, isbn, id, q} = 
GET http://localhost:8000/books/search/?title=Risk HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc2MDQ3LCJpYXQiOjE3NDc0NzI0NDcsImp0aSI6IjU3NzZkZGE1MTA4NDRkOGI5MjVhMGQ5M2ZkOWE1NjEyIiwidXNlcl9pZCI6MX0.iis3CDZXcJECGqVHspFcivUFTaeEoW77-yKSBIMhhTM


### //returnare catri dupa categorie
# category_map = {
#             "recent": "q=fiction&orderBy=newest",
#             "popular": "q=bestseller&orderBy=relevance",
#         } sau orice categorie W
GET http://localhost:8000/api/books/category/?name=popular HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODM4Mjk5LCJpYXQiOjE3NDU4MzQ2OTksImp0aSI6IjZmZDhkNjFlYzBkOTRkMzdiNjFmOTAyMDUxZWQ2ODhjIiwidXNlcl9pZCI6NX0.r0ni4RZ6oMRQyTobj5wS9Cx59dcECqPo0aFa0ry9UxE

//recent = Recently Published
//popular = Popular Now

### //adaugare o care la read
POST http://localhost:8000/books/read/add/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MzY4NzIwLCJpYXQiOjE3NDYzNjUxMjAsImp0aSI6ImJjOTRlMDM3NjVlMTRjMWI4MjQwZGQxOGI2ZmFhNjJhIiwidXNlcl9pZCI6Mn0.dcFL3pFj4UtQslQ7pHt6FbtG-25OEbWoRxvQF_2fSOA
Content-Type: application/json

  
  {
      "book": {
          "ISBN": "978123456789489",
          "id" : "Jx9atwAACAAJ",
          "title": "Example Book",
          "author": "John Doe",
          "genre": "Romance",
          "rating": 4.5,
          "nr_pages": 320,
          "publication_year": 2021,
          "series": "Example Series",
          "description": "This is an example book description."
      }
  }



//testare rcomanadari
###
GET http://localhost:8000/api/books/recommendation/history/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODM4Mjk5LCJpYXQiOjE3NDU4MzQ2OTksImp0aSI6IjZmZDhkNjFlYzBkOTRkMzdiNjFmOTAyMDUxZWQ2ODhjIiwidXNlcl9pZCI6NX0.r0ni4RZ6oMRQyTobj5wS9Cx59dcECqPo0aFa0ry9UxE

### // recomandari generalizate
GET http://localhost:8000/books/recommendation/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDYyMTAwLCJpYXQiOjE3NDcwNTg1MDAsImp0aSI6IjgzMjU1ZmNjN2IwZjQzY2I4YTA2NzYxNThhMGZkZjhlIiwidXNlcl9pZCI6Mn0.Py_J4zcBvmw43HJXtEdQsBAlqanTIjd4Jvz_w1EQgik

### // Continue Reading add
POST http://localhost:8000/api/books/currently_reading/add/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODMzNTA4LCJpYXQiOjE3NDU4Mjk5MDgsImp0aSI6ImI0MDY5MmExMGM5NTRkYWE4NjNkOTdkYzZlYzBkMDg5IiwidXNlcl9pZCI6NX0.B-MrXf62jvFqiUMAu5C6rFywzwPmeJ7Slb37J_rtIDo

{
    "book": {
        "ISBN": "9781234567899",
        "title": "Example Book",
        "author": "John Doe",
        "genre": "Romance",
        "rating": 4.5,
        "nr_pages": 320,
        "publication_year": 2021,
        "series": "Example Series",
        "description": "This is an example book description."
    }
}


### 

POST http://localhost:8000/books/read_list/add/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MzY4NzIwLCJpYXQiOjE3NDYzNjUxMjAsImp0aSI6ImJjOTRlMDM3NjVlMTRjMWI4MjQwZGQxOGI2ZmFhNjJhIiwidXNlcl9pZCI6Mn0.dcFL3pFj4UtQslQ7pHt6FbtG-25OEbWoRxvQF_2fSOA

{
    "book": {
        "ISBN": "9781234567899999010",
        "id" : "Jx9atwAACAAJ",
        "title": "Example Book",
        "author": "John Doe",
        "genre": "Romance",
        "rating": 4.5,
        "nr_pages": 320,
        "publication_year": 2021,
        "series": "Example Series",
        "description": "This is an example book description.",
        "thumbnail": "http://books.google.com/books/content?id=oh-5AAmboMUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    }
}
###
DELETE http://localhost:8000/api/books/read_list/remove/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODQyNDk1LCJpYXQiOjE3NDU4Mzg4OTUsImp0aSI6ImE1M2YxZTE5Nzc5MzRiYTZiN2ExYWIzZjM0ZGRiYzZlIiwidXNlcl9pZCI6NX0.LTSo8XJV04JNRm0hQHZD4olxuJxnbG_QpPuO8cawZJI

{
    
    "ISBN": "9781234567899"
     
}

###
GET http://localhost:8000/api/books/read/get/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODQyNDk1LCJpYXQiOjE3NDU4Mzg4OTUsImp0aSI6ImE1M2YxZTE5Nzc5MzRiYTZiN2ExYWIzZjM0ZGRiYzZlIiwidXNlcl9pZCI6NX0.LTSo8XJV04JNRm0hQHZD4olxuJxnbG_QpPuO8cawZJI

###
GET http://localhost:8000/api/books/get/9781234567890 HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODQyNDk1LCJpYXQiOjE3NDU4Mzg4OTUsImp0aSI6ImE1M2YxZTE5Nzc5MzRiYTZiN2ExYWIzZjM0ZGRiYzZlIiwidXNlcl9pZCI6NX0.LTSo8XJV04JNRm0hQHZD4olxuJxnbG_QpPuO8cawZJI
### 






# --- POSTS ---


###

POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email" : "anamariarusu063@gmail.com",
    "password" : "12345678Abc"

}
###

POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email" : "anamaria2934r@gmail.com",
    "password" : "12345678Abc"

}
###

### Follow 
PATCH http://localhost:8000/api/accounts/profile/2/follow/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4ODIxLCJpYXQiOjE3NDc0NzUyMjEsImp0aSI6ImE1NzNhMTQwNDFjMTQxYzViYWRkOGViNzk4MThjZDhjIiwidXNlcl9pZCI6MX0.PuG1Q08DcUugGvqRm8iS9XsHfy1vH6QNQs1kON84PBA

{}
### Follow 
PATCH http://localhost:8000/api/accounts/profile/1/follow/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4Nzg1LCJpYXQiOjE3NDc0NzUxODUsImp0aSI6IjRkZjgwNjhlMDcwYTRlMjc4MWE1MDllZjRmMGYyZDU5IiwidXNlcl9pZCI6Mn0.ADLOfjPAtYF-AV_a7yDoHq5r6tYEXZItjtzgaRphs6A
Content-Type: application/json

{}

###

GET http://localhost:8000/api/accounts/profile/read/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc5MjMxLCJpYXQiOjE3NDc0NzU2MzEsImp0aSI6ImRiZGIwYTc5MTMxYjQ0ODRiZmI0YzYyZWYwYzJkN2EwIiwidXNlcl9pZCI6MX0.ecl08pu0qgqTKnbG7vCQhb_Ama_AZitKqUkO3uhx5k4

###

GET http://localhost:8000/api/accounts/profile/read/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4Nzg1LCJpYXQiOjE3NDc0NzUxODUsImp0aSI6IjRkZjgwNjhlMDcwYTRlMjc4MWE1MDllZjRmMGYyZDU5IiwidXNlcl9pZCI6Mn0.ADLOfjPAtYF-AV_a7yDoHq5r6tYEXZItjtzgaRphs6A



###
GET http://localhost:8000/posts/feed/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4Nzg1LCJpYXQiOjE3NDc0NzUxODUsImp0aSI6IjRkZjgwNjhlMDcwYTRlMjc4MWE1MDllZjRmMGYyZDU5IiwidXNlcl9pZCI6Mn0.ADLOfjPAtYF-AV_a7yDoHq5r6tYEXZItjtzgaRphs6A

###
# vedem toate postarile unui user -OK
GET http://localhost:8000/posts/ 
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc5MjMxLCJpYXQiOjE3NDc0NzU2MzEsImp0aSI6ImRiZGIwYTc5MTMxYjQ0ODRiZmI0YzYyZWYwYzJkN2EwIiwidXNlcl9pZCI6MX0.ecl08pu0qgqTKnbG7vCQhb_Ama_AZitKqUkO3uhx5k4
###
# vedem postrea cu id 22 -OK
GET http://localhost:8000/posts/9/ 
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4ODIxLCJpYXQiOjE3NDc0NzUyMjEsImp0aSI6ImE1NzNhMTQwNDFjMTQxYzViYWRkOGViNzk4MThjZDhjIiwidXNlcl9pZCI6MX0.PuG1Q08DcUugGvqRm8iS9XsHfy1vH6QNQs1kON84PBA
### 
# modificam postreacu id 22 -OK
PATCH http://localhost:8000/posts/9/update/ 
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4ODIxLCJpYXQiOjE3NDc0NzUyMjEsImp0aSI6ImE1NzNhMTQwNDFjMTQxYzViYWRkOGViNzk4MThjZDhjIiwidXNlcl9pZCI6MX0.PuG1Q08DcUugGvqRm8iS9XsHfy1vH6QNQs1kON84PBA
Content-Type: application/json

{
  "description": "AAAAAA"
}
### 
# stergem postrea cu id 22 -OK
DELETE http://localhost:8000/posts/29/delete/ 
Authorization: JWT  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MTA5MDgxLCJpYXQiOjE3NDgxMDU0ODEsImp0aSI6IjNkNWU3MjE4ZThjMTQ2ZmY5NjU1OWZjYWMxZTFkYjM1IiwidXNlcl9pZCI6MX0.ycTy6Z2YuiUV6jghPP4boqFiBuGy08rh2RwRZxz6R6Q
### 
# facem o postarea de tip "want_to_read" -OK
POST http://localhost:8000/posts/add/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4ODIxLCJpYXQiOjE3NDc0NzUyMjEsImp0aSI6ImE1NzNhMTQwNDFjMTQxYzViYWRkOGViNzk4MThjZDhjIiwidXNlcl9pZCI6MX0.PuG1Q08DcUugGvqRm8iS9XsHfy1vH6QNQs1kON84PBA
Content-Type: application/json

{
  "action": "want_to_read",
  "id": "yow0EAAAQBAJ"
}
### 
# facem o postare de tip "post" -OK
POST http://localhost:8000/posts/add/
Authorization: JWT  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4ODIxLCJpYXQiOjE3NDc0NzUyMjEsImp0aSI6ImE1NzNhMTQwNDFjMTQxYzViYWRkOGViNzk4MThjZDhjIiwidXNlcl9pZCI6MX0.PuG1Q08DcUugGvqRm8iS9XsHfy1vH6QNQs1kON84PBA
Content-Type: application/json

{
  "action": "post",
  "description": "Mi-a plăcut cum arată coperta!",
  "id": "yow0EAAAQBAJ"
  
}

### 
# facem o postare de tip "review" -OK
POST http://localhost:8000/posts/add/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDc4ODIxLCJpYXQiOjE3NDc0NzUyMjEsImp0aSI6ImE1NzNhMTQwNDFjMTQxYzViYWRkOGViNzk4MThjZDhjIiwidXNlcl9pZCI6MX0.PuG1Q08DcUugGvqRm8iS9XsHfy1vH6QNQs1kON84PBA
Content-Type: application/json

{
  "action": "review",
  "rating": 4,
  "description": "SUPERR!",
  "id": "yow0EAAAQBAJ"
}







###
#postari de tip made_progress

POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email" : "anamariarusu063@gmail.com",
    "password" : "12345678Abc"

}

###


POST http://localhost:8000/posts/add/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MTA5NzMwLCJpYXQiOjE3NDgxMDYxMzAsImp0aSI6IjhiM2Q3YzNiYzVhODRhNGM5NjA1MDhkMGI4YTM0ZTNmIiwidXNlcl9pZCI6MX0._QYLvh_YDcIzZOEXJn-DRfi1voBJbVHoByxxGzTJ4RU
Content-Type: application/json

{
  "action": "made_progress",
  "pages_read": 10,
  "id": "yow0EAAAQBAJ"
}



###

GET http://localhost:8000/posts/ 
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MTA5NzMwLCJpYXQiOjE3NDgxMDYxMzAsImp0aSI6IjhiM2Q3YzNiYzVhODRhNGM5NjA1MDhkMGI4YTM0ZTNmIiwidXNlcl9pZCI6MX0._QYLvh_YDcIzZOEXJn-DRfi1voBJbVHoByxxGzTJ4RU









# extensia REST CLIENT nu gestioneaza ok fisiere media | testam cu httpie in terminal cu comanda de mai jos | aici este un exemplu de postare de tip "post" cu 2 fisiere media -OK
# http -f POST http://localhost:8000/posts/add/ Authorization:"JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MTg0NTkxLCJpYXQiOjE3NDYxODA5OTEsImp0aSI6IjY3NjhkMmYwZTYwMTRmYThhYTEyZjM2ZTQxMGJmZWFkIiwidXNlcl9pZCI6MX0.hkwIxmRCV-TPbXzier_S52kFKDbNx_v9_SPeRK3oXnM" action="post" description="Mi-a plăcut cum arată coperta!" ISBN="9781234567890" media@D:/GitHubRepo/LectioSphere/mysite/profile_pics/test.png media@D:/GitHubRepo/LectioSphere/mysite/profile_pics/test.png


### // your friends are reading
GET http://localhost:8000/api/books/get_friends_books/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1ODQyNDk1LCJpYXQiOjE3NDU4Mzg4OTUsImp0aSI6ImE1M2YxZTE5Nzc5MzRiYTZiN2ExYWIzZjM0ZGRiYzZlIiwidXNlcl9pZCI6NX0.LTSo8XJV04JNRm0hQHZD4olxuJxnbG_QpPuO8cawZJI



# ----- PROFIL -----
### GET profil utilizator
GET http://localhost:8000/api/accounts/profile/read/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MzAwODE2LCJpYXQiOjE3NDYyOTcyMTYsImp0aSI6IjliZWZmNTRiMTgzZjQ0ZDE5ZTE3YWVmNTVlZjcyMDZlIiwidXNlcl9pZCI6MX0.rhxS16xrhJttvf-jqFbYG-Kl1fRf2ZkYhwWZ1aWsS_A

###

### PATCH profil utilizator
PATCH http://localhost:8000/api/accounts/profile/update/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MzAwODE2LCJpYXQiOjE3NDYyOTcyMTYsImp0aSI6IjliZWZmNTRiMTgzZjQ0ZDE5ZTE3YWVmNTVlZjcyMDZlIiwidXNlcl9pZCI6MX0.rhxS16xrhJttvf-jqFbYG-Kl1fRf2ZkYhwWZ1aWsS_A

{
  "bio": "sal!",
  "first_name": "Dani",
  "last_name": "Nedelcu",
  "username": "dani240"
}





# - - - CAUTARE USERI - - -

###

GET http://localhost:8000/api/accounts/profiles/search/?username=anarusu
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2NjM2LCJpYXQiOjE3NDczMzMwMzYsImp0aSI6ImI1YjJjZTYyZmY2ZTRkNWZiZjQ5YTI4ZTZhMzk3Mjk0IiwidXNlcl9pZCI6MX0.DAVI2JaO16U5c1S13-vxVxQYyL3Dulm_8KdkXahTdNc
###

GET http://localhost:8000/api/accounts/profiles/search/?first_name=ana
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2NjM2LCJpYXQiOjE3NDczMzMwMzYsImp0aSI6ImI1YjJjZTYyZmY2ZTRkNWZiZjQ5YTI4ZTZhMzk3Mjk0IiwidXNlcl9pZCI6MX0.DAVI2JaO16U5c1S13-vxVxQYyL3Dulm_8KdkXahTdNc
###

GET http://localhost:8000/api/accounts/profiles/search/?last_name=rus
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2NjM2LCJpYXQiOjE3NDczMzMwMzYsImp0aSI6ImI1YjJjZTYyZmY2ZTRkNWZiZjQ5YTI4ZTZhMzk3Mjk0IiwidXNlcl9pZCI6MX0.DAVI2JaO16U5c1S13-vxVxQYyL3Dulm_8KdkXahTdNc
###

GET http://localhost:8000/api/accounts/profiles/search/?first_name=ana&last_name=ru
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2NjM2LCJpYXQiOjE3NDczMzMwMzYsImp0aSI6ImI1YjJjZTYyZmY2ZTRkNWZiZjQ5YTI4ZTZhMzk3Mjk0IiwidXNlcl9pZCI6MX0.DAVI2JaO16U5c1S13-vxVxQYyL3Dulm_8KdkXahTdNc
###

GET http://localhost:8000/api/accounts/profiles/search/?q=ana
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2NjM2LCJpYXQiOjE3NDczMzMwMzYsImp0aSI6ImI1YjJjZTYyZmY2ZTRkNWZiZjQ5YTI4ZTZhMzk3Mjk0IiwidXNlcl9pZCI6MX0.DAVI2JaO16U5c1S13-vxVxQYyL3Dulm_8KdkXahTdNc
###


