# Generated by Django 5.2 on 2025-05-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
