# Generated by Django 5.2 on 2025-04-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
        ('accounts', '0003_rename_name_useraccount_first_name_and_more'),
    ]

    operations = [
    ]
