# Generated by Django 5.1.7 on 2025-03-25 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')], verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
