# Generated by Django 5.1.7 on 2025-03-25 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Book Title')),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Author')),
                ('genre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Library Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='api.user', verbose_name='User')),
            ],
        ),
    ]
