# Generated by Django 5.2 on 2025-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='action',
            field=models.CharField(choices=[('want_to_read', 'Want to Read'), ('made_progress', 'Made Progress'), ('finished_reading', 'Finished Reading'), ('review', 'Review'), ('post', 'Post')], help_text='Select the type of post: characters, version, theme, rating, reviews, posters.', max_length=50, verbose_name='Action'),
        ),
    ]
