# Generated by Django 5.2 on 2025-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_action_alter_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='path',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Media File'),
        ),
    ]
