# Generated by Django 5.2 on 2025-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_media_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(default='default.jpg', upload_to='posts_pics', verbose_name='Media File'),
        ),
    ]
